name = "yaaog"
type = 'webpack'
account_id = ''
route = 'yaaog.hguandl.com/*'
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"
site = {bucket = "./dist",entry-point = "workers-site"}
